### ISSUE TITLE
Skybox appearing behind object

### ISSUE THREAD

**Issue by alfianridwan** [omid3098/Unity-URP-GlassShader#5]
Not sure why but the skybox is appearing on the material itself, even when there are objects behind it.

**Comment by omid3098** [comment]
I don't fully understand your problem. Please provide more details and add images or videos of the problem you have and describe the result you expect to see.

**Comment by omid3098** [comment]
Also if you don't see anything behind the glass, make sure Opaque texture is active in your pipeline asset:
![image](https://github.com/omid3098/Unity-URP-GlassShader/assets/6388730/48230ae0-0b12-47c8-8263-80ee5279337e)

**Comment by alfianridwan** [comment]
Yes, opaque texture is active on the active URP pipeline asset.

This is what I see: https://share.getcloudapp.com/P8u2n5rJ

Even though I've set the camera background to Solid colour, it is the object with the glass shader is rendering the skybox on itself.

See screenshot: https://share.getcloudapp.com/P8u2n5rJ

Apologies in advanced if I'm missing something, but I followed all your Readme instructions and even created a new Unity 3D URP project. Im relatively new to Unity, so I seek your patience and understanding 🙏

**Comment by omid3098** [comment]
It is a little strange.
I tried to reproduce that, and everything is looking ok:
![image](https://github.com/omid3098/Unity-URP-GlassShader/assets/6388730/baa26bd6-3343-4b0f-b64d-7a174142621a)

My camera settings:
![image](https://github.com/omid3098/Unity-URP-GlassShader/assets/6388730/22bd7630-e674-4f63-b869-ba5f19934615)


Environment settings:
![image](https://github.com/omid3098/Unity-URP-GlassShader/assets/6388730/d5fc305a-5271-4e48-9a7b-002111bb8a5d)

Can you try another version of Unity? I don't have your exact version installed.
