### ISSUE TITLE
No submenu options in shader settings as shown in screenshot/demo video

### ISSUE THREAD

**Issue by alfianridwan** [omid3098/Unity-URP-GlassShader#6]
Using Unity 2020.3.17f1

Also has Hidden/InternalShaderError on the Material when first importing. Not sure if that may cause the error.

**Comment by omid3098** [comment]
Thank you for the report. It is not happening here, so if there is a way to reproduce the issue, feel free to re-open the issue.

**Comment by alfianridwan** [comment]
This is what I see on the Shader options on the Inspector panel for Unity 2020.3.17f1, nothing else.

https://share.getcloudapp.com/12u7GobK

All instructions to use were followed based on README.

The same applies to a newly created Unity 3D URP project as well.

**Comment by omid3098** [comment]
Oh, those options are provided in newer versions of ShaderGraph and Unity. It is not a thing I can do much about that.

P.S. you can share you images directly in github. just copy yout image in your clipboard and paste (ctrl-v) in the comment. it will be something like this:
```
![image](https://github.com/omid3098/Unity-URP-GlassShader/assets/6388730/3945c831-1c51-471c-9f73-a0ca888a3744)
```
and you can preview the image in the preview tab:
![image](https://github.com/omid3098/Unity-URP-GlassShader/assets/6388730/475134a2-e538-4cb4-ab15-828e6bcde79a)
